export const GAME_CONFIG = {
  SPEEDS: { NORMAL: 1, FAST: 2, VERY_FAST: 8, ULTRA: 32, MAX: 1000 } as const,
  COMBAT: { ROUND_INTERVAL_HOURS: 1 },
  PRODUCTION: { BASE_HOURS: 336 },
  HP: { REGEN_PER_TICK: 10 },
  NOTIFICATION: { DURATION_HOURS: 6 },
} as const
