import { NextResponse } from 'next/server';
import path from 'path';
import { readFile } from 'fs/promises';
import { existsSync } from 'fs';

export async function GET() {
  try {
    // Try to load the generated initialUnitPlacement.ts as plain text and parse it
    const filePath = path.join(process.cwd(), 'app', 'data', 'map', 'initialUnitPlacement.ts');

    if (!existsSync(filePath)) {
      return NextResponse.json({ placement: {}, armyGroupDefs: {} });
    }

    const source = await readFile(filePath, 'utf-8');

    // Extract the initialUnitPlacement object literal via a simple JSON-section parse.
    // The file is generated by the save route and follows a predictable format.
    const placementMatch = source.match(
      /export const initialUnitPlacement[^=]*=\s*(\{[\s\S]*?\}) as UnitPlacementData;/
    );
    const armyGroupMatch = source.match(
      /export const initialArmyGroupDefs[^=]*=\s*(\{[\s\S]*?\}) as Record<CountryId, ArmyGroupDef\[\]>;/
    );

    let placement = {};
    let armyGroupDefs = {};

    if (placementMatch) {
      try {
        // Convert the TS object literal to JSON-parseable format
        const jsonStr = placementMatch[1]
          .replace(/\/\/[^\n]*/g, '') // strip line comments
          .replace(/,\s*([}\]])/g, '$1') // strip trailing commas
          .replace(/([{,]\s*)([a-zA-Z_$][a-zA-Z0-9_$-]*)\s*:/g, '$1"$2":') // quote unquoted keys
          .replace(/:\s*'([^']*)'/g, ': "$1"'); // single -> double quotes for string values
        placement = JSON.parse(jsonStr);
      } catch {
        // If parsing fails, return empty
      }
    }

    if (armyGroupMatch) {
      try {
        const jsonStr = armyGroupMatch[1]
          .replace(/\/\/[^\n]*/g, '')
          .replace(/,\s*([}\]])/g, '$1')
          .replace(/([{,]\s*)([a-zA-Z_$][a-zA-Z0-9_$-]*)\s*:/g, '$1"$2":')
          .replace(/:\s*'([^']*)'/g, ': "$1"');
        armyGroupDefs = JSON.parse(jsonStr);
      } catch {
        // ignore
      }
    }

    return NextResponse.json({ placement, armyGroupDefs });
  } catch (error) {
    console.error('Error loading unit placement:', error);
    return NextResponse.json({ placement: {}, armyGroupDefs: {} });
  }
}
